# SPDX-FileCopyrightText: The vmnet-helper authors
# SPDX-License-Identifier: Apache-2.0

[tool.pytest.ini_options]
# Use *_test.py naming convention for easier tab completion
python_files = "*_test.py"
python_classes = "Test*"
python_functions = "test_*"
# Show extra test summary info for all except passed
addopts = "-ra"
# Shorter log format for live logs
log_cli_format = "%(name)s: %(message)s"

[tool.basedpyright]
typeCheckingMode = "standard"

[tool.codespell]
# Ignore words in the ignore file.
ignore-words = ".codespell-ignore"

# Skip git and build directories
skip = "./.git,./build"

# Check spelling in file names.
check-filenames = true
