# am i supposed to add these copyright lines idk??
# SPDX-FileCopyrightText: The vmnet-helper authors
# SPDX-License-Identifier: Apache-2.0

name: Weekly Health Check

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
    call-test:
      uses: ./.github/workflows/test.yaml
      permissions:
        contents: read
        
    call-integration:
      needs: call-test
      uses: ./.github/workflows/integration.yaml
      permissions:
        contents: read
        
